const wordData = [
    { word: "abuse", meaning: "滥用；虐待；辱骂", example: "Drug abuse can lead to serious health problems. 药物滥用会导致严重的健康问题。" },
    { word: "motivation", meaning: "动机；动力；积极性", example: "Her main motivation for studying hard is to get into a good university. 她努力学习的主要动机是进入一所好大学。" },
    { word: "dynamic", meaning: "动态的；有活力的", example: "The dynamic nature of the market requires constant adaptation. 市场的动态特性需要不断适应。" },
    { word: "enthusiastic", meaning: "热情的；热心的；热烈的", example: "The teacher was enthusiastic about the new teaching method. 老师对新的教学方法充满热情。" },
    { word: "dominate", meaning: "支配；控制；占优势", example: "The company dominates the global smartphone market. 这家公司主导着全球智能手机市场。" },
    { word: "disturb", meaning: "打扰；妨碍；使不安", example: "Please don't disturb me while I'm working. 我工作时请不要打扰我。" },
    { word: "stick", meaning: "粘贴；刺；戳；枝条", example: "He used glue to stick the pieces together. 他用胶水把这些碎片粘在一起。" },
    { word: "slice", meaning: "切；割；切片；薄片", example: "Could you slice the bread for me? 你能帮我把面包切片吗？" },
    { word: "stream", meaning: "溪流；小河；流动", example: "We sat by the stream and listened to the water flowing. 我们坐在小溪边听流水声。" },
    { word: "instruct", meaning: "指导；指示；教授", example: "The manual instructs users on how to assemble the furniture. 手册指导用户如何组装家具。" },
    { word: "draw on", meaning: "利用；凭借；临近", example: "She drew on her experience to solve the problem. 她凭借自己的经验解决了这个问题。" },
    { word: "outlive", meaning: "比…… 活得长；比…… 经久", example: "She outlived her husband by ten years. 她比丈夫多活了十年。" },
    { word: "adequate", meaning: "足够的；适当的；胜任的", example: "The food was adequate but not outstanding. 食物足够但不突出。" },
    { word: "neutral", meaning: "中立的；中性的；中立者", example: "Switzerland remained neutral during the war. 瑞士在战争期间保持中立。" },
    { word: "evolution", meaning: "演变；进化；发展", example: "The theory of evolution explains the diversity of life. 进化论解释了生命的多样性。" },
    { word: "be accustomed to", meaning: "习惯于", example: "I'm accustomed to getting up early. 我习惯早起。" },
    { word: "glue", meaning: "胶水；胶；v.粘贴", example: "I need some glue to fix this broken vase. 我需要一些胶水来修复这个破碎的花瓶。" },
    { word: "count", meaning: "重要；计算", example: "Every vote counts in an election. 在选举中每一票都很重要。" },
    { word: "mindlessness", meaning: "无意识；没头脑；精神缺失", example: "The mindlessness of the task made it boring. 这项任务的无意识性使它变得无聊。" },
    { word: "envious", meaning: "羡慕的；嫉妒的", example: "She was envious of her friend's success. 她羡慕朋友的成功。" },
    { word: "envy", meaning: "羡慕；嫉妒", example: "His new car was the envy of all his friends. 他的新车是他所有朋友羡慕的对象。" },
    { word: "bitter", meaning: "苦的；痛苦的；辛酸的", example: "The medicine had a bitter taste. 这药有苦味。" },
    { word: "drop out", meaning: "退出；辍学；脱离", example: "He dropped out of college to start his own business. 他从大学辍学开始自己的事业。" },
    { word: "temporarily", meaning: "暂时地；临时地", example: "The office is temporarily closed for renovations. 办公室因装修暂时关闭。" },
    { word: "discipline", meaning: "纪律；学科；训练", example: "Good discipline is essential in the military. 良好的纪律在军队中是必不可少的。" },
    { word: "rugged", meaning: "崎岖的；坚固的；坚毅的", example: "The rugged terrain made hiking difficult. 崎岖的地形使徒步旅行变得困难。" },
    { word: "scenic", meaning: "风景优美的；舞台的；戏剧性的", example: "We took the scenic route along the coast. 我们沿着海岸走了风景优美的路线。" },
    { word: "safari", meaning: "旅行；狩猎远征；旅行队", example: "We went on a safari in Africa last summer. 去年夏天我们去非洲进行了狩猎旅行。" },
    { word: "resistant", meaning: "抵抗的；有抵抗力的；抵抗者", example: "These plants are resistant to drought. 这些植物耐旱。" },
    { word: "sympathetic", meaning: "同情的；同意的", example: "She was sympathetic to my problems. 她对我的问题表示同情。" },
    { word: "initiate", meaning: "开始；发起；使初步了解", example: "The company initiated a new training program. 公司启动了一个新的培训计划。" },
    { word: "shallow", meaning: "浅的；肤浅的", example: "The water is too shallow for swimming here. 这里的水太浅，不适合游泳。" },
    { word: "advocate", meaning: "提倡；拥护；倡导者", example: "She advocates for women's rights. 她倡导妇女权利。" },
    { word: "casually", meaning: "随便地；偶然地；临时地", example: "He mentioned it casually in conversation. 他在谈话中随便提到了这件事。" },
    { word: "clumsily", meaning: "笨拙地；粗陋地；不灵活地", example: "He clumsily knocked over the vase. 他笨拙地打翻了花瓶。" },
    { word: "accomplished", meaning: "有成就的；熟练的；完成的", example: "She is an accomplished pianist. 她是一位有成就的钢琴家。" },
    { word: "demanding", meaning: "要求高的；苛求的", example: "Being a doctor is a demanding job. 医生是一份要求很高的工作。" },
    { word: "revival", meaning: "复兴；复活；苏醒", example: "There has been a revival of interest in traditional crafts. 人们对传统工艺的兴趣有所复兴。" },
    { word: "conscience", meaning: "良心；道德心", example: "His conscience wouldn't allow him to lie. 他的良心不允许他撒谎。" },
    { word: "cautious", meaning: "谨慎的；小心的；慎重的", example: "Be cautious when crossing the street. 过马路时要小心。" },
    { word: "sustainability", meaning: "可持续性；能保持性；永续性", example: "The company focuses on environmental sustainability. 公司注重环境的可持续性。" },
    { word: "taste", meaning: "体验；品尝", example: "Would you like to taste this new dish? 你想尝尝这道新菜吗？" },
    { word: "inspect", meaning: "检查；检验；审视", example: "The mechanic inspected the car's engine. 机械师检查了汽车的发动机。" },
    { word: "wage", meaning: "工资；薪水；开展；进行", example: "The workers demanded higher wages. 工人们要求更高的工资。" },
    { word: "composition", meaning: "成分；作文", example: "The composition of this metal includes copper and zinc. 这种金属的成分包括铜和锌。" },
    { word: "consistent", meaning: "一致的；始终如一的", example: "Her work is always consistent in quality. 她的工作质量始终如一。" },
    { word: "pride oneself on", meaning: "以…… 为自豪；对…… 感到得意", example: "He prides himself on his punctuality. 他以守时为荣。" },
    { word: "cosy", meaning: "舒适的；惬意的", example: "We spent a cosy evening by the fireplace. 我们在壁炉旁度过了一个舒适的夜晚。" },
    { word: "fatigue", meaning: "疲劳；疲倦", example: "After the long hike, we felt extreme fatigue. 长途跋涉后，我们感到极度疲劳。" },
    { word: "afford", meaning: "买得起；负担得起", example: "We can't afford a vacation this year. 今年我们负担不起度假的费用。" },
    { word: "conservative", meaning: "保守的；守旧的", example: "He has very conservative views on education. 他对教育有非常保守的看法。" },
    { word: "obvious", meaning: "明显的；显然的", example: "It's obvious that she's unhappy with the decision. 很明显她对决定不满意。" },
    { word: "awaken", meaning: "v.唤醒", example: "The noise awakened me from my sleep. 噪音把我从睡梦中惊醒。" },
    { word: "cast", meaning: "投掷；投射（光、影等）", example: "The tree cast a long shadow in the evening sun. 树在夕阳下投下长长的影子。" },
    { word: "disqualify", meaning: "取消…… 的资格；使不合格", example: "He was disqualified from the race for cheating. 他因作弊被取消比赛资格。" },
    { word: "conventional", meaning: "传统的；惯例的", example: "They had a conventional wedding ceremony. 他们举行了传统的婚礼仪式。" },
    { word: "craft", meaning: "v.精心制作；n.工艺；手艺", example: "She crafts beautiful jewelry by hand. 她手工制作漂亮的珠宝。" },
    { word: "initiative", meaning: "主动性；倡议", example: "She showed great initiative in solving the problem. 她在解决问题时表现出极大的主动性。" },
    { word: "transform", meaning: "改变", example: "The new manager transformed the company's culture. 新经理改变了公司的文化。" },
    { word: "dedicate", meaning: "奉献；把…… 用于", example: "She dedicated her life to helping the poor. 她毕生致力于帮助穷人。" },
    { word: "partnership", meaning: "伙伴关系；合作关系", example: "The two companies formed a strategic partnership. 两家公司形成了战略伙伴关系。" },
    { word: "innovative", meaning: "创新的；革新的", example: "The company is known for its innovative products. 该公司以其创新产品而闻名。" },
    { word: "save up", meaning: "储蓄；存钱", example: "I'm saving up to buy a new computer. 我正在存钱买一台新电脑。" },
    { word: "immerse", meaning: "使沉浸在；使专心于", example: "She immersed herself in her studies. 她专心于学习。" },
    { word: "authentic", meaning: "真正的；真实的", example: "This restaurant serves authentic Italian food. 这家餐厅供应正宗的意大利食物。" },
    { word: "launch", meaning: "发起；发射", example: "The company will launch a new product next month. 公司将于下月推出新产品。" },
    { word: "respectively", meaning: "分别地；各自地", example: "John and Jane are 10 and 12 years old, respectively. 约翰和简分别为10岁和12岁。" },
    { word: "approach", meaning: "方法；靠近", example: "We need a new approach to solve this problem. 我们需要一种新的方法来解决这个问题。" },
    { word: "route", meaning: "路线", example: "What's the quickest route to the airport? 去机场最快的路线是什么？" },
    { word: "as scheduled", meaning: "按照预定时间；如期", example: "The meeting will proceed as scheduled. 会议将如期进行。" },
    { word: "adore", meaning: "热爱；爱慕，崇拜", example: "She adores her little brother. 她非常疼爱她的小弟弟。" },
    { word: "owe to", meaning: "归功于；欠（钱等）", example: "I owe my success to my parents' support. 我的成功归功于我父母的支持。" },
    { word: "pioneering", meaning: "开拓性的；首创的", example: "He did pioneering work in computer science. 他在计算机科学领域做了开创性的工作。" },
    { word: "abnormally", meaning: "不正常地", example: "The weather is abnormally warm for this time of year. 对于一年中的这个时候来说，天气异常温暖。" },
    { word: "address", meaning: "1.写姓名地址；2.向..说话；3.处理", example: "The president will address the nation tonight. 总统今晚将向全国发表讲话。" },
    { word: "incredible", meaning: "难以置信的；极好的", example: "The view from the top was incredible. 从顶部看到的景色令人难以置信。" },
    { word: "wrap", meaning: "包，裹；（用手臂等）围住", example: "Could you wrap this gift for me? 你能帮我把这个礼物包起来吗？" },
    { word: "floor", meaning: "地板；楼层", example: "The book fell to the floor. 书掉到了地板上。" },
    { word: "irresistible", meaning: "不可抗拒的；极具吸引力的", example: "The chocolate cake looked irresistible. 巧克力蛋糕看起来令人无法抗拒。" },
    { word: "attachment", meaning: "附件；依恋", example: "I sent the document with an attachment. 我发送了带有附件的文档。" },
    { word: "straightforward", meaning: "简单的；坦率的", example: "The instructions are straightforward and easy to follow. 说明简单易懂。" },
    { word: "absent", meaning: "不存在；缺席", example: "Three students were absent today. 今天有三个学生缺席。" },
    { word: "put aside", meaning: "把...放在一边", example: "Let's put aside our differences and work together. 让我们把分歧放在一边，一起工作。" },
    { word: "call off", meaning: "取消", example: "They had to call off the picnic because of the rain. 因为下雨，他们不得不取消野餐。" },
    { word: "cover", meaning: "足够支付", example: "Does your salary cover all your expenses? 你的工资够支付你所有的开支吗？" },
    { word: "take off", meaning: "起飞；脱下", example: "The plane will take off in 10 minutes. 飞机将在10分钟后起飞。" },
    { word: "catch on", meaning: "理解，明白；流行起来", example: "The new fashion trend is starting to catch on. 新的时尚潮流开始流行起来。" },
    { word: "kick off", meaning: "开球；（使）开始；踢开", example: "The event will kick off at 7 pm. 活动将于晚上7点开始。" },
    { word: "spring up", meaning: "迅速出现；突然兴起；跳起", example: "New businesses are springing up all over town. 新企业正在全镇迅速涌现。" },
    { word: "get around", meaning: "到处走动", example: "It's hard to get around the city without a car. 没有汽车很难在城市里到处走动。" },
    { word: "unpaved", meaning: "未铺砌的；未铺面的", example: "The road was unpaved and full of potholes. 这条路没有铺砌，到处都是坑洼。" },
    { word: "steep", meaning: "陡峭的；（价格等）过高的", example: "The hill was too steep for me to climb. 这座山太陡了，我爬不上去。" },
    { word: "winding", meaning: "蜿蜒的；曲折的", example: "We drove along a winding mountain road. 我们沿着蜿蜒的山路行驶。" },
    { word: "prohibit", meaning: "禁止；阻止", example: "Smoking is prohibited in this building. 这栋楼禁止吸烟。" },
    { word: "documentary", meaning: "纪录片；纪实的", example: "We watched a documentary about climate change. 我们看了一部关于气候变化的纪录片。" },
    { word: "receiver", meaning: "接收者；接收器", example: "Please hold the receiver to your ear. 请将听筒放在耳边。" },
    { word: "credit as", meaning: "把…… 归功于；认为…… 具有（某种优点或特点）", example: "She is credited as the inventor of the device. 她被认为是该设备的发明者。" },
    { word: "insightful", meaning: "有洞察力的；富有见地的", example: "His comments were very insightful. 他的评论非常有见地。" },
    { word: "picky", meaning: "挑剔的；吹毛求疵的", example: "She's very picky about her food. 她对食物非常挑剔。" },
    { word: "hesitant", meaning: "犹豫的；踌躇的", example: "He seemed hesitant to answer the question. 他似乎对回答这个问题犹豫不决。" },
    { word: "exposed", meaning: "暴露的；易受伤害的", example: "The plants were exposed to strong winds. 这些植物暴露在强风中。" },
    { word: "collapse", meaning: "倒塌；崩溃", example: "The old building collapsed during the earthquake. 旧建筑在地震中倒塌了。" },
    { word: "reveal", meaning: "揭示；显示", example: "The investigation revealed new evidence. 调查揭示了新的证据。" },
    { word: "destruction", meaning: "破坏；毁灭", example: "The hurricane caused widespread destruction. 飓风造成了广泛的破坏。" },
    { word: "irrigation", meaning: "灌溉；水利工程", example: "The fields require regular irrigation. 这些田地需要定期灌溉。" },
    { word: "meditation", meaning: "冥想；沉思", example: "She practices meditation every morning. 她每天早上练习冥想。" },
    { word: "transformative", meaning: "变革性的；起改造作用的", example: "The internet has had a transformative effect on society. 互联网对社会产生了变革性的影响。" },
    { word: "go viral", meaning: "走红；像病毒般传播开来", example: "The video went viral on social media. 该视频在社交媒体上走红。" },
    { word: "replacement", meaning: "替换；替代品", example: "We need to find a replacement for the broken part. 我们需要找到损坏部件的替代品。" },
    { word: "be immersed in", meaning: "沉浸于；专心于", example: "He was completely immersed in his book. 他完全沉浸在书中。" },
    { word: "leisurely", meaning: "悠闲的；从容不迫的", example: "We took a leisurely walk along the beach. 我们沿着海滩悠闲地散步。" },
    { word: "youngster", meaning: "年轻人；少年", example: "The program is designed for youngsters aged 12-16. 该计划专为12-16岁的年轻人设计。" },
    { word: "interact", meaning: "互动；相互作用", example: "The teacher encourages students to interact in class. 老师鼓励学生在课堂上互动。" },
    { word: "offbeat", meaning: "不寻常的；另类的", example: "She has an offbeat sense of humor. 她有一种另类的幽默感。" },
    { word: "sample", meaning: "v.品尝；体验", example: "Would you like to sample our new product? 你想尝尝我们的新产品吗？" },
    { word: "tailor", meaning: "v.专门制作", example: "The program is tailored to individual needs. 该计划是根据个人需求量身定制的。" },
    { word: "call for", meaning: "要求；呼吁", example: "The situation calls for immediate action. 这种情况需要立即采取行动。" },
    { word: "isolated", meaning: "孤立的；偏远的；隔绝的", example: "The village is very isolated in winter. 这个村庄在冬天非常孤立。" },
    { word: "course", meaning: "课程；科目；过程；进程;一道菜", example: "I'm taking a course in computer programming. 我正在学习计算机编程课程。" },
    { word: "extinct", meaning: "灭绝的；绝种的", example: "Dinosaurs have been extinct for millions of years. 恐龙已经灭绝了数百万年。" },
    { word: "babysit", meaning: "临时照看婴儿", example: "My sister babysits for our neighbors. 我姐姐为邻居照看孩子。" },
    { word: "take over", meaning: "控制；接管", example: "The new manager will take over next week. 新经理将于下周接管。" },
    { word: "go off", meaning: "（警报器等）突然发出巨响；", example: "The fire alarm went off in the middle of the night. 火灾警报在半夜突然响起。" },
    { word: "claim", meaning: "找回；声称；", example: "You can claim your luggage at the baggage carousel. 您可以在行李传送带上取回行李。" },
    { word: "expansive", meaning: "广阔的；广泛的", example: "He has an expansive knowledge of history. 他有广泛的历史知识。" },
    { word: "trail", meaning: "踪迹；小径", example: "We followed the trail through the forest. 我们沿着小径穿过森林。" },
    { word: "appealing", meaning: "有吸引力的；恳求的", example: "The idea of a holiday was very appealing. 度假的想法很有吸引力。" },
    { word: "unmatched", meaning: "无与伦比的；不相配的", example: "Her beauty is unmatched in the kingdom. 她的美丽在王国中是无与伦比的。" },
    { word: "feature", meaning: "特征；以…… 为特色", example: "The new model features improved safety. 新车型的特点是提高了安全性。" },
    { word: "resistance", meaning: "抵抗；阻力", example: "The bacteria show resistance to antibiotics. 细菌对抗生素表现出抗药性。" },
    { word: "promising", meaning: "有前途的；有希望的", example: "She's a promising young athlete. 她是一个有前途的年轻运动员。" },
    { word: "applicable", meaning: "适用的；可应用的", example: "This rule is not applicable in all situations. 这条规则并非在所有情况下都适用。" },
    { word: "be position as", meaning: "被定位为；被视为", example: "The product is positioned as a luxury item. 该产品被定位为奢侈品。" },
    { word: "competent", meaning: "有能力的；胜任的", example: "He is competent to handle the job. 他有能力处理这项工作。" },
    { word: "fulfilling", meaning: "令人满足的；有成就感的", example: "Teaching is a very fulfilling career. 教学是一项非常有成就感的职业。" },
    { word: "sort", meaning: "n.种类；v.分类", example: "What sort of music do you like? 你喜欢哪种音乐？" },
    { word: "competence", meaning: "能力；胜任", example: "Her competence as a manager is unquestionable. 她作为经理的能力是毋庸置疑的。" },
    { word: "ethics", meaning: "道德准则", example: "Medical ethics prevent doctors from harming patients. 医学道德准则防止医生伤害病人。" },
    { word: "categorize", meaning: "分类；归类", example: "The books are categorized by subject. 这些书按主题分类。" },
    { word: "undermine", meaning: "破坏；削弱", example: "Constant criticism can undermine confidence. 不断的批评会削弱信心。" },
    { word: "tirelessly", meaning: "不知疲倦地；坚持不懈地", example: "She worked tirelessly to help the poor. 她不知疲倦地帮助穷人。" },
    { word: "overdue", meaning: "迟到的；早该发生的", example: "This reform is long overdue. 这项改革早就该进行了。" },
    { word: "revival", meaning: "复兴；复苏", example: "There has been a revival of interest in classical music. 人们对古典音乐的兴趣有所复苏。" },
    { word: "exceptional", meaning: "非凡的；例外的", example: "She showed exceptional talent at an early age. 她在很小的时候就表现出了非凡的才能。" },
    { word: "multiple", meaning: "多个的；多样的", example: "The decision was based on multiple factors. 这个决定是基于多种因素做出的。" },
    { word: "discrimination", meaning: "歧视；辨别", example: "Racial discrimination is illegal. 种族歧视是非法的。" },
    { word: "prospect", meaning: "前景；可能性", example: "The job offers good prospects for advancement. 这份工作提供了良好的晋升前景。" },
    { word: "foresight", meaning: "远见；先见之明", example: "With great foresight, she invested in the company early. 凭借远见卓识，她很早就投资了这家公司。" },
    { word: "revolution", meaning: "革命；变革", example: "The industrial revolution changed society dramatically. 工业革命极大地改变了社会。" },
    { word: "encounter", meaning: "遭遇；邂逅", example: "I encountered an old friend at the airport. 我在机场遇到了一位老朋友。" },
    { word: "assign", meaning: "分配；指派", example: "The teacher assigned homework for the weekend. 老师布置了周末的家庭作业。" },
    { word: "essence", meaning: "本质；精华", example: "The essence of his argument was that we need change. 他论点的本质是我们需要改变。" },
    { word: "distinct", meaning: "明显的；独特的", example: "There's a distinct smell of coffee in the air. 空气中有一股明显的咖啡味。" },
    { word: "aggressive", meaning: "好斗的；有进取心的", example: "The company has an aggressive marketing strategy. 该公司采取了积极的营销策略。" },
    { word: "compromise", meaning: "妥协；损害", example: "We reached a compromise that satisfied both sides. 我们达成了令双方都满意的妥协。" },
    { word: "hatred", meaning: "仇恨；憎恶", example: "His speech was full of hatred and anger. 他的演讲充满了仇恨和愤怒。" },
    { word: "restoration", meaning: "恢复；修复", example: "The restoration of the old building took two years. 这座旧建筑的修复花了两年时间。" },
    { word: "estranged", meaning: "疏远的；分离的", example: "He is estranged from his family. 他与家人疏远了。" },
    { word: "barely", meaning: "几乎不；勉强", example: "I barely had time to catch my train. 我几乎没有时间赶上火车。" },
    { word: "abundant", meaning: "丰富的；充裕的", example: "The region is abundant in natural resources. 该地区自然资源丰富。" },
    { word: "distinguish", meaning: "区分；辨别", example: "It's hard to distinguish the twins apart. 很难区分这对双胞胎。" },
    { word: "redefine", meaning: "重新定义；再解释", example: "The company aims to redefine the industry standards. 公司旨在重新定义行业标准。" },
    { word: "ongoing", meaning: "进行中的；持续的", example: "The investigation is still ongoing. 调查仍在进行中。" },
    { word: "emerging", meaning: "新兴的；出现的", example: "China is an emerging economic power. 中国是一个新兴的经济强国。" },
    { word: "fiction", meaning: "小说", example: "She enjoys reading science fiction. 她喜欢读科幻小说。" },
    { word: "radiant", meaning: "容光焕发的；光芒四射的", example: "The bride looked radiant on her wedding day. 新娘在婚礼当天看起来容光焕发。" },
    { word: "oppose", meaning: "反对；对抗", example: "Many people oppose the new law. 许多人反对这项新法律。" },
    { word: "appeal to", meaning: "呼吁；吸引", example: "The charity appeals to people's generosity. 该慈善机构呼吁人们的慷慨解囊。" },
    { word: "skeptical", meaning: "怀疑的；持怀疑态度的", example: "I'm skeptical about his promises. 我对他的承诺持怀疑态度。" },
    { word: "valid", meaning: "有效的；合理的", example: "Your passport must be valid for six months. 你的护照必须有六个月的有效期。" },
    { word: "opponent", meaning: "对手；反对者", example: "He defeated his opponent in the debate. 他在辩论中击败了对手。" },
    { word: "unavoidably", meaning: "不可避免地；必然地", example: "The decision will unavoidably lead to job losses. 这一决定将不可避免地导致失业。" },
    { word: "flaw", meaning: "缺陷；瑕疵", example: "There's a flaw in your argument. 你的论点有缺陷。" },
    { word: "violate", meaning: "违反；侵犯", example: "The company violated environmental regulations. 该公司违反了环境法规。" },
    { word: "in all respects", meaning: "在各方面；从各方面来说", example: "The project was successful in all respects. 该项目在各方面都很成功。" },
    { word: "review", meaning: "复习；回顾", example: "I need to review my notes before the exam. 我需要在考试前复习笔记。" },
    { word: "complicate", meaning: "使复杂；使陷入", example: "His interference only complicated matters. 他的干涉只会使事情复杂化。" },
    { word: "momentary", meaning: "短暂的；瞬间的", example: "There was a momentary silence after his remark. 他的话说完后，出现了短暂的沉默。" },
    { word: "echo", meaning: "附和；回声", example: "Her words echoed in my mind. 她的话在我脑海中回荡。" },
    { word: "insert", meaning: "插入；嵌入", example: "Insert the key into the lock. 将钥匙插入锁中。" },
    { word: "take in", meaning: "吸收；理解", example: "It took me a while to take in the news. 我花了一些时间才理解这个消息。" },
    { word: "expertly", meaning: "熟练地；专业地", example: "She expertly handled the difficult situation. 她熟练地处理了这一困难局面。" },
    { word: "garment", meaning: "衣服；服装", example: "The garment industry employs many people. 服装行业雇佣了许多人。" },
    { word: "invisible", meaning: "看不见的；无形的", example: "The stars are invisible during the day. 星星在白天是看不见的。" },
    { word: "absence", meaning: "缺席；缺乏", example: "His absence was noticed by everyone. 他的缺席被所有人注意到了。" },
    { word: "dignity", meaning: "尊严；高贵", example: "He maintained his dignity throughout the trial. 在整个审判过程中，他保持了自己的尊严。" },
    { word: "to one's full potential", meaning: "充分发挥潜力；尽某人最大潜能", example: "The program helps students develop to their full potential. 该计划帮助学生充分发挥潜力。" },
    { word: "consistently", meaning: "一贯地；始终如一地", example: "She has consistently performed well in her job. 她在工作中一直表现良好。" },
    { word: "ensure", meaning: "确保；保证", example: "Please ensure that all windows are closed. 请确保所有窗户都关闭。" },
    { word: "indicate", meaning: "表明；指示", example: "The results indicate a need for further research. 结果表明需要进一步研究。" },
    { word: "deny", meaning: "否认；拒绝", example: "He denied any involvement in the crime. 他否认与犯罪有任何牵连。" },
    { word: "presence", meaning: "存在；出席", example: "Your presence at the meeting is required. 你必须出席会议。" },
    { word: "ashamed", meaning: "羞愧的；惭愧的", example: "I'm ashamed of my behavior yesterday. 我为昨天的行为感到羞愧。" },
    { word: "take out", meaning: "取出；去掉", example: "Don't forget to take out the trash. 别忘了把垃圾拿出去。" },
    { word: "refreshing", meaning: "提神的；令人耳目一新的", example: "The swim was refreshing on a hot day. 在炎热的一天游泳令人神清气爽。" },
    { word: "ambitious", meaning: "有雄心的；野心勃勃的", example: "She has ambitious plans for her career. 她对自己的职业有雄心勃勃的计划。" },
    { word: "attach to", meaning: "附属于；使依恋", example: "Please attach the file to your email. 请将文件附加到您的电子邮件中。" },
    { word: "neglect", meaning: "忽视；疏忽", example: "Don't neglect your health. 不要忽视你的健康。" },
    { word: "engage in", meaning: "从事；参加", example: "They engaged in a lively discussion. 他们进行了热烈的讨论。" },
    { word: "accomplish", meaning: "完成；实现", example: "She worked hard to accomplish her goals. 她努力实现了自己的目标。" },  

    { word: "beneficial", meaning: "有益的；有利的", example: "Reading daily is beneficial to your vocabulary. 每天阅读对你的词汇量有益。" },  

    { word: "consume", meaning: "消耗；消费", example: "The car consumes a lot of fuel. 这辆车耗油量很大。" },  

    { word: "diligent", meaning: "勤奋的；用功的", example: "He is a diligent student who always studies hard. 他是个勤奋的学生，总是努力学习。" },  

    { word: "essential", meaning: "必要的；基本的", example: "Water is essential for survival. 水是生存的必需品。" },  

    { word: "flexible", meaning: "灵活的；柔韧的", example: "A good leader should be flexible in decision-making. 一个好的领导在决策上应该灵活。" },  

    { word: "generate", meaning: "产生；生成", example: "Solar panels generate electricity from sunlight. 太阳能电池板利用阳光发电。" },  

    { word: "hesitate", meaning: "犹豫；迟疑", example: "Don’t hesitate to ask for help if you need it. 如果需要帮助，不要犹豫。" },  

    { word: "innovative", meaning: "创新的；革新的", example: "The company is known for its innovative products. 这家公司以其创新产品闻名。" },  

    { word: "justify", meaning: "证明…合理；为…辩护", example: "Can you justify your decision with evidence? 你能用证据证明你的决定合理吗？" },
];


const pronunciationData = {
    "abuse": "/əˈbjuːs/",
    "motivation": "/ˌməʊtɪˈveɪʃən/",
    "dynamic": "/daɪˈnæmɪk/",
    "enthusiastic": "/ɪnˌθjuːziˈæstɪk/",
    "dominate": "/ˈdɒmɪneɪt/",
    "disturb": "/dɪˈstɜːb/",
    "stick": "/stɪk/",
    "slice": "/slaɪs/",
    "stream": "/striːm/",
    "instruct": "/ɪnˈstrʌkt/",
    "draw on": "/drɔː ɒn/",
    "outlive": "/aʊtˈlɪv/",
    "adequate": "/ˈædɪkwət/",
    "neutral": "/ˈnjuːtrəl/",
    "evolution": "/ˌiːvəˈluːʃən/",
    "be accustomed to": "/biː əˈkʌstəmd tuː/",
    "glue": "/ɡluː/",
    "count": "/kaʊnt/",
    "mindlessness": "/ˈmaɪndləsnəs/",
    "envious": "/ˈenviəs/",
    "envy": "/ˈenvi/",
    "bitter": "/ˈbɪtə(r)/",
    "drop out": "/drɒp aʊt/",
    "temporarily": "/ˈtempərərɪli/",
    "discipline": "/ˈdɪsəplɪn/",
    "rugged": "/ˈrʌɡɪd/",
    "scenic": "/ˈsiːnɪk/",
    "safari": "/səˈfɑːri/",
    "resistant": "/rɪˈzɪstənt/",
    "sympathetic": "/ˌsɪmpəˈθetɪk/",
    "initiate": "/ɪˈnɪʃieɪt/",
    "shallow": "/ˈʃæləʊ/",
    "advocate": "/ˈædvəkeɪt/",
    "casually": "/ˈkæʒuəli/",
    "clumsily": "/ˈklʌmzɪli/",
    "accomplished": "/əˈkʌmplɪʃt/",
    "demanding": "/dɪˈmɑːndɪŋ/",
    "revival": "/rɪˈvaɪvl/",
    "conscience": "/ˈkɒnʃəns/",
    "cautious": "/ˈkɔːʃəs/",
    "sustainability": "/səˌsteɪnəˈbɪləti/",
    "taste": "/teɪst/",
    "inspect": "/ɪnˈspekt/",
    "wage": "/weɪdʒ/",
    "composition": "/ˌkɒmpəˈzɪʃən/",
    "consistent": "/kənˈsɪstənt/",
    "pride oneself on": "/praɪd wʌnˈself ɒn/",
    "cosy": "/ˈkəʊzi/",
    "fatigue": "/fəˈtiːɡ/",
    "afford": "/əˈfɔːd/",
    "conservative": "/kənˈsɜːvətɪv/",
    "obvious": "/ˈɒbviəs/",
    "awaken": "/əˈweɪkən/",
    "cast": "/kɑːst/",
    "disqualify": "/dɪsˈkwɒlɪfaɪ/",
    "conventional": "/kənˈvenʃənl/",
    "craft": "/krɑːft/",
    "initiative": "/ɪˈnɪʃətɪv/",
    "transform": "/trænsˈfɔːm/",
    "dedicate": "/ˈdedɪkeɪt/",
    "partnership": "/ˈpɑːtnəʃɪp/",
    "innovative": "/ˈɪnəveɪtɪv/",
    "save up": "/seɪv ʌp/",
    "immerse": "/ɪˈmɜːs/",
    "authentic": "/ɔːˈθentɪk/",
    "launch": "/lɔːntʃ/",
    "respectively": "/rɪˈspektɪvli/",
    "approach": "/əˈprəʊtʃ/",
    "route": "/ruːt/",
    "as scheduled": "/æz ˈʃedjuːld/",
    "adore": "/əˈdɔː(r)/",
    "owe to": "/əʊ tuː/",
    "pioneering": "/ˌpaɪəˈnɪərɪŋ/",
    "abnormally": "/æbˈnɔːməli/",
    "address": "/əˈdres/",
    "incredible": "/ɪnˈkredəbl/",
    "wrap": "/ræp/",
    "floor": "/flɔː(r)/",
    "irresistible": "/ˌɪrɪˈzɪstəbl/",
    "attachment": "/əˈtætʃmənt/",
    "straightforward": "/ˌstreɪtˈfɔːwəd/",
    "absent": "/ˈæbsənt/",
    "put aside": "/pʊt əˈsaɪd/",
    "call off": "/kɔːl ɒf/",
    "cover": "/ˈkʌvə(r)/",
    "take off": "/teɪk ɒf/",
    "catch on": "/kætʃ ɒn/",
    "kick off": "/kɪk ɒf/",
    "spring up": "/sprɪŋ ʌp/",
    "get around": "/ɡet əˈraʊnd/",
    "unpaved": "/ˌʌnˈpeɪvd/",
    "steep": "/stiːp/",
    "winding": "/ˈwaɪndɪŋ/",
    "prohibit": "/prəˈhɪbɪt/",
    "documentary": "/ˌdɒkjuˈmentri/",
    "receiver": "/rɪˈsiːvə(r)/",
    "credit as": "/ˈkredɪt æz/",
    "insightful": "/ˈɪnsaɪtfʊl/",
    "picky": "/ˈpɪki/",
    "hesitant": "/ˈhezɪtənt/",
    "exposed": "/ɪkˈspəʊzd/",
    "collapse": "/kəˈlæps/",
    "reveal": "/rɪˈviːl/",
    "destruction": "/dɪˈstrʌkʃən/",
    "irrigation": "/ˌɪrɪˈɡeɪʃən/",
    "meditation": "/ˌmedɪˈteɪʃən/",
    "transformative": "/trænsˈfɔːmətɪv/",
    "go viral": "/ɡəʊ ˈvaɪrəl/",
    "replacement": "/rɪˈpleɪsmənt/",
    "be immersed in": "/biː ɪˈmɜːst ɪn/",
    "leisurely": "/ˈleʒəli/",
    "youngster": "/ˈjʌŋstə(r)/",
    "interact": "/ˌɪntərˈækt/",
    "offbeat": "/ˌɒfˈbiːt/",
    "sample": "/ˈsɑːmpl/",
    "tailor": "/ˈteɪlə(r)/",
    "call for": "/kɔːl fɔː(r)/",
    "isolated": "/ˈaɪsəleɪtɪd/",
    "course": "/kɔːs/",
    "extinct": "/ɪkˈstɪŋkt/",
    "babysit": "/ˈbeɪbisɪt/",
    "take over": "/teɪk ˈəʊvə(r)/",
    "go off": "/ɡəʊ ɒf/",
    "claim": "/kleɪm/",
    "expansive": "/ɪkˈspænsɪv/",
    "trail": "/treɪl/",
    "appealing": "/əˈpiːlɪŋ/",
    "unmatched": "/ˌʌnˈmætʃt/",
    "feature": "/ˈfiːtʃə(r)/",
    "resistance": "/rɪˈzɪstəns/",
    "promising": "/ˈprɒmɪsɪŋ/",
    "applicable": "/əˈplɪkəbl/",
    "be position as": "/biː pəˈzɪʃən æz/",
    "competent": "/ˈkɒmpɪtənt/",
    "fulfilling": "/fʊlˈfɪlɪŋ/",
    "sort": "/sɔːt/",
    "competence": "/ˈkɒmpɪtəns/",
    "ethics": "/ˈeθɪks/",
    "categorize": "/ˈkætəɡəraɪz/",
    "undermine": "/ˌʌndəˈmaɪn/",
    "tirelessly": "/ˈtaɪələsli/",
    "overdue": "/ˌəʊvəˈdjuː/",
    "revival": "/rɪˈvaɪvl/",
    "exceptional": "/ɪkˈsepʃənl/",
    "multiple": "/ˈmʌltɪpl/",
    "discrimination": "/dɪˌskrɪmɪˈneɪʃən/",
    "prospect": "/ˈprɒspekt/",
    "foresight": "/ˈfɔːsaɪt/",
    "revolution": "/ˌrevəˈluːʃən/",
    "encounter": "/ɪnˈkaʊntə(r)/",
    "assign": "/əˈsaɪn/",
    "essence": "/ˈesns/",
    "distinct": "/dɪˈstɪŋkt/",
    "aggressive": "/əˈɡresɪv/",
    "compromise": "/ˈkɒmprəmaɪz/",
    "hatred": "/ˈheɪtrɪd/",
    "restoration": "/ˌrestəˈreɪʃən/",
    "estranged": "/ɪˈstreɪndʒd/",
    "barely": "/ˈbeəli/",
    "abundant": "/əˈbʌndənt/",
    "distinguish": "/dɪˈstɪŋɡwɪʃ/",
    "redefine": "/ˌriːdɪˈfaɪn/",
    "ongoing": "/ˈɒnɡəʊɪŋ/",
    "emerging": "/ɪˈmɜːdʒɪŋ/",
    "fiction": "/ˈfɪkʃn/",
    "radiant": "/ˈreɪdiənt/",
    "oppose": "/əˈpəʊz/",
    "appeal to": "/əˈpiːl tuː/",
    "skeptical": "/ˈskeptɪkl/",
    "valid": "/ˈvælɪd/",
    "opponent": "/əˈpəʊnənt/",
    "unavoidably": "/ˌʌnəˈvɔɪdəbli/",
    "flaw": "/flɔː/",
    "violate": "/ˈvaɪəleɪt/",
    "in all respects": "/ɪn ɔːl rɪˈspekts/",
    "review": "/rɪˈvjuː/",
    "complicate": "/ˈkɒmplɪkeɪt/",
    "momentary": "/ˈməʊməntri/",
    "echo": "/ˈekəʊ/",
    "insert": "/ɪnˈsɜːt/",
    "take in": "/teɪk ɪn/",
    "expertly": "/ˈekspɜːtli/",
    "garment": "/ˈɡɑːmənt/",
    "invisible": "/ɪnˈvɪzəbl/",
    "absence": "/ˈæbsəns/",
    "dignity": "/ˈdɪɡnəti/",
    "to one's full potential": "/tuː wʌnz fʊl pəˈtenʃl/",
    "consistently": "/kənˈsɪstəntli/",
    "ensure": "/ɪnˈʃʊə(r)/",
    "indicate": "/ˈɪndɪkeɪt/",
    "deny": "/dɪˈnaɪ/",
    "presence": "/ˈprezns/",
    "ashamed": "/əˈʃeɪmd/",
    "take out": "/teɪk aʊt/",
    "refreshing": "/rɪˈfreʃɪŋ/",
    "ambitious": "/æmˈbɪʃəs/",
    "attach to": "/əˈtætʃ tuː/",
    "neglect": "/nɪˈɡlekt/",
    "engage in": "/ɪnˈɡeɪdʒ ɪn/",
    "accomplish": "/əˈkʌmplɪʃ/",
    "beneficial": "/ˌbenɪˈfɪʃl/",
    "consume": "/kənˈsjuːm/",
    "diligent": "/ˈdɪlɪdʒənt/",
    "essential": "/ɪˈsenʃl/",
    "flexible": "/ˈfleksəbl/",
    "generate": "/ˈdʒenəreɪt/",
    "hesitate": "/ˈhezɪteɪt/",
    "innovative": "/ˈɪnəveɪtɪv/",
    "justify": "/ˈdʒʌstɪfaɪ/"
};